# import :D

In [408]:
import pandas as pd
import sys 
print(sys.version)
print("pandas version",pd.__version__)

3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
pandas version 2.3.3

# I/O (reading and writing)

In [409]:
# creating dataframe from dictionary 
data={
    "Name":["Phrolova","Ami","Me:D"],
    "Age":[500,400,20],
    "is_love":[True,True,False]
}
df = pd.DataFrame(data)
df

       Name  Age  is_love
0  Phrolova  500     True
1       Ami  400     True
2      Me:D   20    False

In [410]:
#readinf a file form excel
df=pd.read_excel("public(2018-2019).xlsx")

In [411]:
df.to_csv("e.csv",index=False)

In [412]:
df=pd.read_csv("idk.csv")

# DataFrame basic

In [413]:
df.head()

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
0,Banteay Meanchey,2018,90.7,6.0,3.3,91.6,4.7,3.7,94.7,3.4,2.0,91.0,2.5,6.4,95.0,1.6,3.4,92.3,1.3,6.4,80.4,2.2,17.3,84.4,1.6,14.0,78.7,2.8,18.4,85.6,0.6,13.8,89.7,0.7,9.6,54.9,5.5,39.7
1,Battambang,2018,83.8,11.7,4.5,88.5,8.0,3.6,88.6,5.7,5.7,90.8,4.0,5.2,91.0,2.7,6.3,89.1,2.3,8.6,76.8,3.3,19.9,81.3,2.2,16.5,78.7,4.3,17.0,82.4,1.2,16.4,87.5,1.2,11.3,66.1,4.6,29.3
2,Kampong Cham,2018,81.6,14.2,4.2,84.4,10.9,4.7,86.5,8.9,4.6,88.0,7.4,4.6,89.8,5.8,4.4,91.2,3.9,4.9,80.1,3.3,16.6,82.1,2.6,15.2,79.5,3.3,17.2,80.0,2.0,18.1,89.9,0.6,9.5,56.6,5.3,38.1
3,Kampong Chhnang,2018,88.0,10.6,1.4,90.3,7.6,2.0,91.5,6.3,2.2,92.5,4.5,3.0,94.5,2.8,2.7,94.0,2.0,4.0,83.5,2.4,14.1,83.3,1.5,15.1,82.0,2.3,15.7,81.9,0.8,17.3,89.2,0.6,10.2,60.2,5.2,34.6
4,Kampong Speu,2018,89.3,8.7,2.0,92.5,6.3,1.2,92.7,4.5,2.8,93.2,3.3,3.5,92.7,2.4,4.9,93.4,3.1,3.5,79.5,1.3,19.2,80.6,0.7,18.6,75.1,2.2,22.7,79.4,0.3,20.3,89.4,0.2,10.4,84.4,1.9,13.7

In [414]:
#id u have many many column pandas might hide some of it and here's how to over write it
pd.set_option("display.max_column",500)
df.head(19)

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
0,Banteay Meanchey,2018,90.7,6.0,3.3,91.6,4.7,3.7,94.7,3.4,2.0,91.0,2.5,6.4,95.0,1.6,3.4,92.3,1.3,6.4,80.4,2.2,17.3,84.4,1.6,14.0,78.7,2.8,18.4,85.6,0.6,13.8,89.7,0.7,9.6,54.9,5.5,39.7
1,Battambang,2018,83.8,11.7,4.5,88.5,8.0,3.6,88.6,5.7,5.7,90.8,4.0,5.2,91.0,2.7,6.3,89.1,2.3,8.6,76.8,3.3,19.9,81.3,2.2,16.5,78.7,4.3,17.0,82.4,1.2,16.4,87.5,1.2,11.3,66.1,4.6,29.3
2,Kampong Cham,2018,81.6,14.2,4.2,84.4,10.9,4.7,86.5,8.9,4.6,88.0,7.4,4.6,89.8,5.8,4.4,91.2,3.9,4.9,80.1,3.3,16.6,82.1,2.6,15.2,79.5,3.3,17.2,80.0,2.0,18.1,89.9,0.6,9.5,56.6,5.3,38.1
3,Kampong Chhnang,2018,88.0,10.6,1.4,90.3,7.6,2.0,91.5,6.3,2.2,92.5,4.5,3.0,94.5,2.8,2.7,94.0,2.0,4.0,83.5,2.4,14.1,83.3,1.5,15.1,82.0,2.3,15.7,81.9,0.8,17.3,89.2,0.6,10.2,60.2,5.2,34.6
4,Kampong Speu,2018,89.3,8.7,2.0,92.5,6.3,1.2,92.7,4.5,2.8,93.2,3.3,3.5,92.7,2.4,4.9,93.4,3.1,3.5,79.5,1.3,19.2,80.6,0.7,18.6,75.1,2.2,22.7,79.4,0.3,20.3,89.4,0.2,10.4,84.4,1.9,13.7
5,Kampong Thom,2018,82.2,13.2,4.6,86.9,9.3,3.7,86.7,7.4,5.9,89.0,4.9,6.1,89.9,3.7,6.4,92.2,2.6,5.3,78.8,3.5,17.6,85.6,1.4,13.0,83.9,3.3,12.9,86.6,0.6,12.8,93.3,0.7,6.0,73.8,2.2,23.9
6,Kampot,2018,89.1,8.6,2.2,92.7,5.0,2.3,91.3,4.3,4.4,94.2,2.8,3.0,92.2,2.1,5.7,92.5,1.7,5.7,80.4,2.2,17.3,81.5,1.4,17.2,79.4,3.5,17.1,81.0,1.1,17.8,90.3,0.7,9.0,77.4,2.1,20.5
7,Kandal,2018,85.8,13.1,1.0,88.3,9.9,1.7,88.7,8.1,3.3,90.6,6.5,2.9,90.6,5.0,4.4,92.8,3.6,3.5,81.2,3.3,15.4,84.4,1.9,13.7,81.9,2.6,15.5,86.0,1.1,12.9,92.8,0.8,6.4,66.9,5.7,27.4
8,Kep,2018,90.6,9.8,NaN,98.0,5.8,NaN,93.8,5.3,0.9,89.2,4.3,6.5,89.8,2.3,7.8,86.0,3.1,10.8,73.5,4.3,22.2,78.5,0.8,20.6,78.6,3.4,17.9,88.9,1.7,9.5,91.2,0.3,8.5,94.5,0.8,4.7
9,Koh Kong,2018,84.8,7.5,7.7,86.2,5.3,8.6,89.8,3.7,6.4,90.0,1.8,8.1,98.7,1.3,0.0,92.4,0.8,6.7,84.6,0.9,14.5,87.3,0.9,11.8,76.0,3.9,20.2,85.1,0.5,14.4,95.4,0.1,4.4,27.4,2.1,70.5
10,Kratie,2018,81.3,13.3,5.4,84.5,9.6,5.9,84.6,7.5,7.9,85.3,6.1,8.6,85.8,4.6,9.7,84.7,3.0,12.3,75.3,2.4,22.3,79.8,0.9,19.3,76.2,2.6,21.2,85.4,0.9,13.7,90.9,0.6,8.5,49.7,4.6,45.6
11,Mondul Kiri,2018,84.9,8.0,7.1,89.3,6.0,4.7,87.6,4.9,7.5,85.8,4.0,10.2,87.0,1.4,11.6,89.8,1.5,8.6,79.3,3.1,17.6,84.8,2.8,12.3,84.0,3.7,12.3,86.2,1.1,12.7,94.9,0.9,4.3,92.9,0.6,6.4
12,Otdar Meanchey,2018,80.1,14.2,5.8,85.3,10.1,4.7,85.8,8.1,6.1,85.3,5.3,9.3,89.3,4.2,6.5,82.9,2.2,14.9,79.0,3.4,17.5,84.1,1.7,14.2,74.8,5.5,19.7,84.3,2.3,13.4,94.4,0.2,5.5,87.8,0.9,11.3
13,Pailin,2018,86.0,9.9,4.1,86.4,7.6,6.0,84.8,8.0,7.2,89.9,5.0,5.1,89.3,3.3,7.4,92.9,0.8,6.4,75.2,7.3,17.5,85.3,3.4,11.3,80.1,2.2,17.7,88.4,1.8,9.8,92.5,1.7,5.8,53.0,10.3,36.7
14,Phnom Penh,2018,90.8,5.6,3.6,93.2,4.0,2.8,94.0,2.7,3.3,96.1,2.0,1.9,95.0,1.8,3.2,94.2,0.8,5.0,85.1,3.2,11.7,92.8,2.3,4.9,86.6,3.3,10.1,90.8,1.1,8.0,NaN,1.1,NaN,49.0,6.9,44.1
15,Preah Sihanouk,2018,91.9,6.1,1.9,94.0,3.7,2.3,96.6,3.0,0.4,91.6,1.9,6.5,95.6,1.7,2.7,87.1,1.7,11.2,71.5,5.2,23.2,81.8,1.7,16.5,73.7,3.7,22.6,86.4,1.0,12.7,91.8,0.6,7.5,78.0,2.0,20.0
16,Preah Vihear,2018,78.9,17.1,4.0,85.2,10.2,4.6,88.4,7.9,3.7,87.4,5.0,7.6,87.9,2.8,9.3,89.0,1.8,9.2,82.0,1.6,16.4,88.4,1.0,10.6,85.2,1.3,13.4,77.4,0.1,22.6,85.4,0.0,14.6,85.3,1.4,13.3
17,Prey Veng,2018,86.2,11.9,1.8,90.6,8.3,1.0,91.1,6.5,2.4,92.0,5.2,2.9,92.3,4.4,3.3,94.0,3.1,2.9,83.1,0.8,16.1,82.9,0.4,16.7,79.3,1.6,19.2,82.1,0.9,17.0,89.5,0.8,9.7,79.3,2.9,17.7
18,Pursat,2018,81.1,14.8,4.2,86.7,9.1,4.3,89.2,7.2,3.5,89.2,5.7,5.1,91.8,3.8,4.4,90.9,2.6,6.6,80.6,1.9,17.5,82.6,1.3,16.2,82.7,2.7,14.6,79.5,1.1,19.4,88.5,0.6,11.0,58.4,4.5,37.2

In [415]:
df.tail()

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
79,Takeo,2020,85.6,12.3,2.1,88.1,9.3,2.6,89.4,7.9,2.7,90.8,6.2,3.0,91.5,5.1,3.4,85.4,4.2,10.3,91.9,1.3,6.9,88.8,1.9,9.3,77.8,1.3,20.9,89.3,0.3,10.4,89.3,0.3,10.4,65.3,2.2,32.5
80,Tbaung Khmum,2020,80.5,14.6,4.9,83.2,10.3,6.5,85.9,8.3,5.8,86.4,6.2,7.4,87.1,5.2,7.7,59.2,3.3,37.5,85.5,1.0,13.5,84.1,0.6,15.3,55.6,3.2,41.2,84.3,0.5,15.3,91.6,0.4,8.0,53.2,3.0,43.8
81,Whole Kingdom,2020,82.1,13.6,4.3,85.5,9.7,4.8,87.4,7.8,4.8,88.3,6.0,5.7,89.0,4.6,6.4,73.4,3.3,23.3,87.2,1.0,11.8,86.5,0.9,12.6,69.4,1.9,28.7,86.5,0.5,13.1,91.6,0.4,8.0,59.2,2.7,38.1
82,- Urban Area,2020,78.8,14.6,6.6,85.3,9.4,5.3,88.3,6.9,4.8,89.3,5.1,5.6,90.8,3.4,5.7,69.2,2.2,28.6,91.1,1.5,7.4,93.0,1.4,5.6,71.6,2.8,25.6,91.9,0.6,7.6,98.2,0.3,1.5,54.7,3.8,41.5
83,- Rural Area,2020,82.8,13.4,3.8,85.5,9.8,4.7,87.2,8.0,4.8,88.1,6.2,5.7,88.7,4.8,6.5,74.3,3.6,22.1,86.2,0.9,12.9,84.8,0.8,14.4,68.7,1.7,29.6,84.4,0.4,15.2,88.8,0.4,10.8,61.3,2.3,36.5

In [416]:
# random subset form row
df.sample(5)

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
22,Svay Rieng,2018,90.4,8.1,1.6,93.4,5.6,1.0,93.9,3.9,2.2,94.1,3.0,2.8,95.4,2.1,2.6,96.3,1.6,2.1,77.2,2.3,20.5,83.5,1.8,14.7,79.4,2.9,17.7,83.4,0.5,16.1,90.3,0.5,9.2,76.1,1.9,21.9
27,- Rural Area,2018,84.9,11.7,3.4,88.3,8.3,3.5,89.1,6.5,4.4,90.3,4.9,4.8,91.1,3.6,5.3,91.0,2.8,6.2,80.0,2.5,17.4,82.8,1.6,15.6,79.1,2.8,18.0,82.7,1.1,16.2,89.0,0.8,10.3,68.5,3.9,27.6
13,Pailin,2018,86.0,9.9,4.1,86.4,7.6,6.0,84.8,8.0,7.2,89.9,5.0,5.1,89.3,3.3,7.4,92.9,0.8,6.4,75.2,7.3,17.5,85.3,3.4,11.3,80.1,2.2,17.7,88.4,1.8,9.8,92.5,1.7,5.8,53.0,10.3,36.7
37,Koh Kong,2019,84.4,8.0,7.6,87.6,5.2,7.2,90.7,3.6,5.7,92.5,2.2,5.3,NaN,0.7,NaN,82.4,1.0,16.6,84.5,0.5,14.9,90.0,0.3,9.8,76.4,1.6,22.0,97.9,0.2,1.9,91.5,0.0,8.5,32.9,2.9,64.1
73,Prey Veng,2020,84.2,13.0,2.8,88.3,9.3,2.4,88.7,8.3,3.0,90.0,6.3,3.6,90.7,5.2,4.2,73.5,4.0,22.4,88.7,0.2,11.1,86.2,0.1,13.7,63.9,1.1,35.0,84.2,0.2,15.6,90.2,0.2,9.6,57.1,2.8,40.1

In [417]:
# if u enter a fraction into the sample it give that fraction of the entire data set
# if my dataset has 20 row enter 0.1 will give 2 row
# random state keep the random stuff the same if we run it again
df.sample(frac=0.1,random_state=42)

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
73,Prey Veng,2020,84.2,13.0,2.8,88.3,9.3,2.4,88.7,8.3,3.0,90.0,6.3,3.6,90.7,5.2,4.2,73.5,4.0,22.4,88.7,0.2,11.1,86.2,0.1,13.7,63.9,1.1,35.0,84.2,0.2,15.6,90.2,0.2,9.6,57.1,2.8,40.1
0,Banteay Meanchey,2018,90.7,6.0,3.3,91.6,4.7,3.7,94.7,3.4,2.0,91.0,2.5,6.4,95.0,1.6,3.4,92.3,1.3,6.4,80.4,2.2,17.3,84.4,1.6,14.0,78.7,2.8,18.4,85.6,0.6,13.8,89.7,0.7,9.6,54.9,5.5,39.7
58,Kampong Cham,2020,80.0,15.9,4.2,82.6,12.1,5.3,85.5,9.8,4.7,86.4,7.7,5.9,88.3,5.9,5.8,60.6,4.3,35.2,87.9,0.9,11.2,86.0,0.9,13.1,61.7,2.2,36.1,86.1,0.5,13.4,90.2,0.8,9.0,55.7,3.0,41.3
22,Svay Rieng,2018,90.4,8.1,1.6,93.4,5.6,1.0,93.9,3.9,2.2,94.1,3.0,2.8,95.4,2.1,2.6,96.3,1.6,2.1,77.2,2.3,20.5,83.5,1.8,14.7,79.4,2.9,17.7,83.4,0.5,16.1,90.3,0.5,9.2,76.1,1.9,21.9
12,Otdar Meanchey,2018,80.1,14.2,5.8,85.3,10.1,4.7,85.8,8.1,6.1,85.3,5.3,9.3,89.3,4.2,6.5,82.9,2.2,14.9,79.0,3.4,17.5,84.1,1.7,14.2,74.8,5.5,19.7,84.3,2.3,13.4,94.4,0.2,5.5,87.8,0.9,11.3
70,Phnom Penh,2020,80.6,10.5,8.9,88.1,7.1,4.7,89.6,5.3,5.1,90.5,4.2,5.3,92.2,2.8,5.1,65.4,1.8,32.8,93.3,1.2,5.5,95.5,1.7,2.8,64.1,3.1,32.7,95.8,0.2,4.0,NaN,0.1,NaN,50.8,5.6,43.6
10,Kratie,2018,81.3,13.3,5.4,84.5,9.6,5.9,84.6,7.5,7.9,85.3,6.1,8.6,85.8,4.6,9.7,84.7,3.0,12.3,75.3,2.4,22.3,79.8,0.9,19.3,76.2,2.6,21.2,85.4,0.9,13.7,90.9,0.6,8.5,49.7,4.6,45.6
18,Pursat,2018,81.1,14.8,4.2,86.7,9.1,4.3,89.2,7.2,3.5,89.2,5.7,5.1,91.8,3.8,4.4,90.9,2.6,6.6,80.6,1.9,17.5,82.6,1.3,16.2,82.7,2.7,14.6,79.5,1.1,19.4,88.5,0.6,11.0,58.4,4.5,37.2

In [418]:
# print a list of all your column in your data frame
df.columns

Index(['Province', 'Year', 'Grade_1_Promotion', 'Grade_1_Repetition',
       'Grade_1_Dropout', 'Grade_2_Promotion', 'Grade_2_Repetition',
       'Grade_2_Dropout', 'Grade_3_Promotion', 'Grade_3_Repetition',
       'Grade_3_Dropout', 'Grade_4_Promotion', 'Grade_4_Repetition',
       'Grade_4_Dropout', 'Grade_5_Promotion', 'Grade_5_Repetition',
       'Grade_5_Dropout', 'Grade_6_Promotion', 'Grade_6_Repetition',
       'Grade_6_Dropout', 'Grade_7_Promotion', 'Grade_7_Repetition',
       'Grade_7_Dropout', 'Grade_8_Promotion', 'Grade_8_Repetition',
       'Grade_8_Dropout', 'Grade_9_Promotion', 'Grade_9_Repetition',
       'Grade_9_Dropout', 'Grade_10_Promotion', 'Grade_10_Repetition',
       'Grade_10_Dropout', 'Grade_11_Promotion', 'Grade_11_Repetition',
       'Grade_11_Dropout', 'Grade_12_Promotion', 'Grade_12_Repetition',
       'Grade_12_Dropout'],
      dtype='object')

In [419]:
# print the index value in the df
df.index

RangeIndex(start=0, stop=84, step=1)

In [420]:
# print the coulumn's data type as well as its size
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Province             84 non-null     object
 1   Year                 84 non-null     int64
 2   Grade_1_Promotion    84 non-null     float64
 3   Grade_1_Repetition   84 non-null     float64
 4   Grade_1_Dropout      82 non-null     float64
 5   Grade_2_Promotion    84 non-null     float64
 6   Grade_2_Repetition   84 non-null     float64
 7   Grade_2_Dropout      80 non-null     float64
 8   Grade_3_Promotion    84 non-null     float64
 9   Grade_3_Repetition   84 non-null     float64
 10  Grade_3_Dropout      82 non-null     float64
 11  Grade_4_Promotion    84 non-null     float64
 12  Grade_4_Repetition   84 non-null     float64
 13  Grade_4_Dropout      83 non-null     float64
 14  Grade_5_Promotion    83 non-null     float64
 15  Grade_5_Repetition   84 non-null     float64
 16  Grade_5_Dropout      83 non-null     float64
 17  Grade_6_Promotion    84 non-null     float64
 18  Grade_6_Repetition   84 non-null     float64
 19  Grade_6_Dropout      84 non-null     float64
 20  Grade_7_Promotion    84 non-null     float64
 21  Grade_7_Repetition   84 non-null     float64
 22  Grade_7_Dropout      84 non-null     float64
 23  Grade_8_Promotion    84 non-null     float64
 24  Grade_8_Repetition   84 non-null     float64
 25  Grade_8_Dropout      84 non-null     float64
 26  Grade_9_Promotion    84 non-null     float64
 27  Grade_9_Repetition   84 non-null     float64
 28  Grade_9_Dropout      84 non-null     float64
 29  Grade_10_Promotion   83 non-null     float64
 30  Grade_10_Repetition  84 non-null     float64
 31  Grade_10_Dropout     83 non-null     float64
 32  Grade_11_Promotion   81 non-null     float64
 33  Grade_11_Repetition  84 non-null     float64
 34  Grade_11_Dropout     80 non-null     float64
 35  Grade_12_Promotion   84 non-null     float64
 36  Grade_12_Repetition  84 non-null     float64
 37  Grade_12_Dropout     84 non-null     float64
dtypes: float64(36), int64(1), object(1)
memory usage: 25.1+ KB

In [421]:
# for a quicker summary
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Columns: 38 entries, Province to Grade_12_Dropout
dtypes: float64(36), int64(1), object(1)
memory usage: 25.1+ KB

In [422]:
# to get descritive statistic
df.describe()
# it can also descrive non numirical stuff if u ask it to it'll give count unique top freq

,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
count,84.000000,84.000000,84.000000,82.000000,84.000000,84.000000,80.000000,84.000000,84.000000,82.000000,84.000000,84.000000,83.000000,83.000000,84.000000,83.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,83.000000,84.000000,83.000000,81.000000,84.000000,80.000000,84.000000,84.000000,84.000000
mean,2019.000000,84.566667,11.282143,4.306098,88.359524,7.725000,4.253750,89.409524,6.038095,4.673171,90.215476,4.353571,5.491566,90.886747,3.152381,5.931325,79.930952,2.275000,17.789286,83.042857,1.842857,15.108333,85.475000,1.191667,13.328571,73.965476,2.635714,23.401190,85.751807,0.734524,13.520482,91.141975,0.439286,8.537500,68.952381,2.936905,28.101190
std,0.821401,4.742790,3.744270,2.475577,4.322514,2.545862,2.289378,3.658547,2.145149,2.331430,3.417971,1.798758,2.721469,3.651120,1.444097,3.080581,13.182911,1.061015,13.112617,4.331679,1.232226,3.795184,4.114619,0.708844,4.132725,10.825578,1.462433,11.006214,4.011792,0.549369,4.013506,3.405836,0.365374,3.307926,14.498014,2.415651,13.947073
min,2018.000000,71.500000,4.600000,0.300000,78.400000,3.200000,0.200000,81.100000,2.400000,0.400000,82.600000,1.500000,0.200000,82.100000,0.700000,0.000000,23.500000,0.100000,2.100000,71.500000,0.100000,5.500000,77.600000,0.000000,1.000000,13.000000,0.600000,10.100000,77.400000,0.000000,1.900000,76.900000,0.000000,0.200000,27.400000,0.000000,4.700000
25%,2018.000000,81.200000,8.700000,2.525000,85.200000,5.800000,2.375000,86.675000,4.300000,2.825000,87.925000,2.875000,3.600000,88.450000,2.100000,3.800000,73.150000,1.400000,6.675000,80.000000,0.900000,12.275000,82.975000,0.700000,11.775000,69.475000,1.600000,16.925000,83.300000,0.300000,11.750000,89.400000,0.100000,7.150000,58.325000,1.575000,17.225000
50%,2019.000000,85.000000,10.700000,3.950000,88.300000,7.450000,4.100000,89.350000,5.950000,4.500000,90.550000,4.300000,5.400000,91.000000,2.800000,5.300000,83.500000,2.250000,14.650000,83.400000,1.700000,15.150000,84.800000,1.100000,13.850000,76.100000,2.350000,20.550000,85.600000,0.600000,13.700000,91.000000,0.400000,8.600000,68.950000,2.450000,27.500000
75%,2020.000000,88.175000,13.650000,5.575000,90.800000,9.525000,5.750000,92.050000,7.800000,6.100000,92.625000,5.700000,6.500000,93.500000,4.100000,7.750000,90.925000,3.025000,24.325000,85.925000,2.500000,17.525000,86.725000,1.700000,15.700000,80.675000,3.300000,27.975000,87.850000,1.100000,16.150000,92.500000,0.700000,10.325000,79.875000,3.700000,38.025000
max,2020.000000,94.900000,22.900000,12.000000,98.800000,14.700000,11.500000,98.100000,11.800000,11.300000,98.000000,10.000000,15.000000,98.700000,8.000000,14.100000,96.300000,5.600000,75.500000,93.300000,7.300000,23.200000,98.500000,3.400000,21.600000,87.500000,9.100000,83.400000,97.900000,2.300000,22.600000,99.700000,1.700000,23.000000,94.500000,18.500000,70.500000

In [423]:
# to get the shape of df
df.shape

(84, 38)

In [424]:
# just the row
len(df)

84

# Subsetting a dataframe

In [425]:
df[['Year','Grade_1_Promotion','Grade_3_Promotion']]

    Year  Grade_1_Promotion  Grade_3_Promotion
0   2018               90.7               94.7
1   2018               83.8               88.6
2   2018               81.6               86.5
3   2018               88.0               91.5
4   2018               89.3               92.7
..   ...                ...                ...
79  2020               85.6               89.4
80  2020               80.5               85.9
81  2020               82.1               87.4
82  2020               78.8               88.3
83  2020               82.8               87.2

[84 rows x 3 columns]

In [426]:
# we can also do it like this
df[df.columns[:5]]
# this is the first 5 columns

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout
0,Banteay Meanchey,2018,90.7,6.0,3.3
1,Battambang,2018,83.8,11.7,4.5
2,Kampong Cham,2018,81.6,14.2,4.2
3,Kampong Chhnang,2018,88.0,10.6,1.4
4,Kampong Speu,2018,89.3,8.7,2.0
...,...,...,...,...,...
79,Takeo,2020,85.6,12.3,2.1
80,Tbaung Khmum,2020,80.5,14.6,4.9
81,Whole Kingdom,2020,82.1,13.6,4.3
82,- Urban Area,2020,78.8,14.6,6.6
83,- Rural Area,2020,82.8,13.4,3.8

In [427]:
# we can also filter column
df[[c for c in df.columns if 'Dropout' in  c]]

,Grade_1_Dropout,Grade_2_Dropout,Grade_3_Dropout,Grade_4_Dropout,Grade_5_Dropout,Grade_6_Dropout,Grade_7_Dropout,Grade_8_Dropout,Grade_9_Dropout,Grade_10_Dropout,Grade_11_Dropout,Grade_12_Dropout
0,3.3,3.7,2.0,6.4,3.4,6.4,17.3,14.0,18.4,13.8,9.6,39.7
1,4.5,3.6,5.7,5.2,6.3,8.6,19.9,16.5,17.0,16.4,11.3,29.3
2,4.2,4.7,4.6,4.6,4.4,4.9,16.6,15.2,17.2,18.1,9.5,38.1
3,1.4,2.0,2.2,3.0,2.7,4.0,14.1,15.1,15.7,17.3,10.2,34.6
4,2.0,1.2,2.8,3.5,4.9,3.5,19.2,18.6,22.7,20.3,10.4,13.7
...,...,...,...,...,...,...,...,...,...,...,...,...
79,2.1,2.6,2.7,3.0,3.4,10.3,6.9,9.3,20.9,10.4,10.4,32.5
80,4.9,6.5,5.8,7.4,7.7,37.5,13.5,15.3,41.2,15.3,8.0,43.8
81,4.3,4.8,4.8,5.7,6.4,23.3,11.8,12.6,28.7,13.1,8.0,38.1
82,6.6,5.3,4.8,5.6,5.7,28.6,7.4,5.6,25.6,7.6,1.5,41.5
83,3.8,4.7,4.8,5.7,6.5,22.1,12.9,14.4,29.6,15.2,10.8,36.5

In [428]:
# we can also filter by type
df.select_dtypes('int')

    Year
0   2018
1   2018
2   2018
3   2018
4   2018
..   ...
79  2020
80  2020
81  2020
82  2020
83  2020

[84 rows x 1 columns]

In [429]:
# noted when we select a single column it'll give a serie 
type(df["Year"])

pandas.core.series.Series

In [430]:
# if er want a dataframe we need to
type(df[["Year"]])

pandas.core.frame.DataFrame

# filterign rows

In [431]:
# df.loc[] use the name
# df.iloc[] use the index number

In [432]:
df.iloc[1,4]

np.float64(4.5)

In [433]:
# using slice
df.iloc[:5,:5]# the first 5 rows and the first 5 columns

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout
0,Banteay Meanchey,2018,90.7,6.0,3.3
1,Battambang,2018,83.8,11.7,4.5
2,Kampong Cham,2018,81.6,14.2,4.2
3,Kampong Chhnang,2018,88.0,10.6,1.4
4,Kampong Speu,2018,89.3,8.7,2.0

In [434]:
# if we use a single number it'll filter to a row
df.iloc[5]

Province               Kampong Thom
Year                           2018
Grade_1_Promotion              82.2
Grade_1_Repetition             13.2
Grade_1_Dropout                 4.6
Grade_2_Promotion              86.9
Grade_2_Repetition              9.3
Grade_2_Dropout                 3.7
Grade_3_Promotion              86.7
Grade_3_Repetition              7.4
Grade_3_Dropout                 5.9
Grade_4_Promotion              89.0
Grade_4_Repetition              4.9
Grade_4_Dropout                 6.1
Grade_5_Promotion              89.9
Grade_5_Repetition              3.7
Grade_5_Dropout                 6.4
Grade_6_Promotion              92.2
Grade_6_Repetition              2.6
Grade_6_Dropout                 5.3
Grade_7_Promotion              78.8
Grade_7_Repetition              3.5
Grade_7_Dropout                17.6
Grade_8_Promotion              85.6
Grade_8_Repetition              1.4
Grade_8_Dropout                13.0
Grade_9_Promotion              83.9
Grade_9_Repetition              3.3
Grade_9_Dropout                12.9
Grade_10_Promotion             86.6
Grade_10_Repetition             0.6
Grade_10_Dropout               12.8
Grade_11_Promotion             93.3
Grade_11_Repetition             0.7
Grade_11_Dropout                6.0
Grade_12_Promotion             73.8
Grade_12_Repetition             2.2
Grade_12_Dropout               23.9
Name: 5, dtype: object

In [435]:
# if we put it in a list it'll filter and put it in a df
df.iloc[[5]]

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
5,Kampong Thom,2018,82.2,13.2,4.6,86.9,9.3,3.7,86.7,7.4,5.9,89.0,4.9,6.1,89.9,3.7,6.4,92.2,2.6,5.3,78.8,3.5,17.6,85.6,1.4,13.0,83.9,3.3,12.9,86.6,0.6,12.8,93.3,0.7,6.0,73.8,2.2,23.9

In [436]:
#filter just the columns
df.iloc[:,[1,5,7]]

    Year  Grade_2_Promotion  Grade_2_Dropout
0   2018               91.6              3.7
1   2018               88.5              3.6
2   2018               84.4              4.7
3   2018               90.3              2.0
4   2018               92.5              1.2
..   ...                ...              ...
79  2020               88.1              2.6
80  2020               83.2              6.5
81  2020               85.5              4.8
82  2020               85.3              5.3
83  2020               85.5              4.7

[84 rows x 3 columns]

In [437]:
#if we want to use loc put in the name
df.loc[:,['Year','Grade_2_Promotion','Grade_5_Promotion']]

    Year  Grade_2_Promotion  Grade_5_Promotion
0   2018               91.6               95.0
1   2018               88.5               91.0
2   2018               84.4               89.8
3   2018               90.3               94.5
4   2018               92.5               92.7
..   ...                ...                ...
79  2020               88.1               91.5
80  2020               83.2               87.1
81  2020               85.5               89.0
82  2020               85.3               90.8
83  2020               85.5               88.7

[84 rows x 3 columns]

In [438]:
# one of the best thing we can do is filter in a boolean expression which give us to go some fun filtering 
df.loc[df['Grade_2_Dropout']== 2]
# we can also put more condition simply put and(&) or (|)

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
3,Kampong Chhnang,2018,88.0,10.6,1.4,90.3,7.6,2.0,91.5,6.3,2.2,92.5,4.5,3.0,94.5,2.8,2.7,94.0,2.0,4.0,83.5,2.4,14.1,83.3,1.5,15.1,82.0,2.3,15.7,81.9,0.8,17.3,89.2,0.6,10.2,60.2,5.2,34.6

In [439]:
# this will print all the stuff except the where the codition met
df.loc[~(df['Grade_2_Dropout']== 2)]

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
0,Banteay Meanchey,2018,90.7,6.0,3.3,91.6,4.7,3.7,94.7,3.4,2.0,91.0,2.5,6.4,95.0,1.6,3.4,92.3,1.3,6.4,80.4,2.2,17.3,84.4,1.6,14.0,78.7,2.8,18.4,85.6,0.6,13.8,89.7,0.7,9.6,54.9,5.5,39.7
1,Battambang,2018,83.8,11.7,4.5,88.5,8.0,3.6,88.6,5.7,5.7,90.8,4.0,5.2,91.0,2.7,6.3,89.1,2.3,8.6,76.8,3.3,19.9,81.3,2.2,16.5,78.7,4.3,17.0,82.4,1.2,16.4,87.5,1.2,11.3,66.1,4.6,29.3
2,Kampong Cham,2018,81.6,14.2,4.2,84.4,10.9,4.7,86.5,8.9,4.6,88.0,7.4,4.6,89.8,5.8,4.4,91.2,3.9,4.9,80.1,3.3,16.6,82.1,2.6,15.2,79.5,3.3,17.2,80.0,2.0,18.1,89.9,0.6,9.5,56.6,5.3,38.1
4,Kampong Speu,2018,89.3,8.7,2.0,92.5,6.3,1.2,92.7,4.5,2.8,93.2,3.3,3.5,92.7,2.4,4.9,93.4,3.1,3.5,79.5,1.3,19.2,80.6,0.7,18.6,75.1,2.2,22.7,79.4,0.3,20.3,89.4,0.2,10.4,84.4,1.9,13.7
5,Kampong Thom,2018,82.2,13.2,4.6,86.9,9.3,3.7,86.7,7.4,5.9,89.0,4.9,6.1,89.9,3.7,6.4,92.2,2.6,5.3,78.8,3.5,17.6,85.6,1.4,13.0,83.9,3.3,12.9,86.6,0.6,12.8,93.3,0.7,6.0,73.8,2.2,23.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Takeo,2020,85.6,12.3,2.1,88.1,9.3,2.6,89.4,7.9,2.7,90.8,6.2,3.0,91.5,5.1,3.4,85.4,4.2,10.3,91.9,1.3,6.9,88.8,1.9,9.3,77.8,1.3,20.9,89.3,0.3,10.4,89.3,0.3,10.4,65.3,2.2,32.5
80,Tbaung Khmum,2020,80.5,14.6,4.9,83.2,10.3,6.5,85.9,8.3,5.8,86.4,6.2,7.4,87.1,5.2,7.7,59.2,3.3,37.5,85.5,1.0,13.5,84.1,0.6,15.3,55.6,3.2,41.2,84.3,0.5,15.3,91.6,0.4,8.0,53.2,3.0,43.8
81,Whole Kingdom,2020,82.1,13.6,4.3,85.5,9.7,4.8,87.4,7.8,4.8,88.3,6.0,5.7,89.0,4.6,6.4,73.4,3.3,23.3,87.2,1.0,11.8,86.5,0.9,12.6,69.4,1.9,28.7,86.5,0.5,13.1,91.6,0.4,8.0,59.2,2.7,38.1
82,- Urban Area,2020,78.8,14.6,6.6,85.3,9.4,5.3,88.3,6.9,4.8,89.3,5.1,5.6,90.8,3.4,5.7,69.2,2.2,28.6,91.1,1.5,7.4,93.0,1.4,5.6,71.6,2.8,25.6,91.9,0.6,7.6,98.2,0.3,1.5,54.7,3.8,41.5
83,- Rural Area,2020,82.8,13.4,3.8,85.5,9.8,4.7,87.2,8.0,4.8,88.1,6.2,5.7,88.7,4.8,6.5,74.3,3.6,22.1,86.2,0.9,12.9,84.8,0.8,14.4,68.7,1.7,29.6,84.4,0.4,15.2,88.8,0.4,10.8,61.3,2.3,36.5

In [440]:
# the query method guve the string representation of the boolean stuff we filteres
avg_drop=df['Grade_6_Dropout'].mean()
filtered_df = df.query('(Year > 2019) and (Grade_6_Dropout >= @avg_drop)')
filtered_df
# we can use outside variable also by pututung in the @ in front

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout
57,Battambang,2020,86.4,10.5,3.1,84.2,9.5,6.3,86.9,6.8,6.3,89.1,4.7,6.1,88.0,3.7,8.4,74.5,2.7,22.8,85.5,0.9,13.7,85.7,0.9,13.4,72.1,2.1,25.8,83.9,0.6,15.5,92.0,0.5,7.6,57.8,3.5,38.7
58,Kampong Cham,2020,80.0,15.9,4.2,82.6,12.1,5.3,85.5,9.8,4.7,86.4,7.7,5.9,88.3,5.9,5.8,60.6,4.3,35.2,87.9,0.9,11.2,86.0,0.9,13.1,61.7,2.2,36.1,86.1,0.5,13.4,90.2,0.8,9.0,55.7,3.0,41.3
60,Kampong Speu,2020,87.1,10.1,2.9,90.5,6.3,3.2,90.0,6.1,3.9,90.8,4.9,4.3,90.7,3.4,5.9,66.4,2.7,30.9,81.0,0.5,18.5,79.6,0.5,19.9,45.2,1.6,53.2,77.6,0.6,21.8,86.5,0.6,13.0,36.0,1.1,62.9
61,Kampong Thom,2020,82.3,14.1,3.7,86.2,8.7,5.1,87.0,7.7,5.3,87.1,5.5,7.4,87.8,3.8,8.4,66.4,3.2,30.4,84.5,0.7,14.8,83.8,0.5,15.7,73.2,1.3,25.5,85.7,0.4,13.9,91.5,0.2,8.3,58.9,1.9,39.2
65,Koh Kong,2020,85.1,9.9,5.0,83.9,7.3,8.8,89.8,4.3,5.9,87.1,2.2,10.7,90.8,2.7,6.5,66.8,1.4,31.8,88.4,1.0,10.6,88.8,1.3,9.9,69.5,3.1,27.3,86.7,0.3,12.9,90.3,0.1,9.6,62.0,1.3,36.7
66,Kratie,2020,78.6,17.1,4.4,81.1,11.9,7.0,83.0,8.8,8.3,84.6,7.4,7.9,84.1,5.0,10.8,66.0,3.8,30.1,81.0,0.9,18.1,82.0,0.5,17.4,70.0,3.0,27.0,85.9,0.0,14.1,92.2,0.0,7.8,69.0,1.2,29.7
68,Otdar Meanchey,2020,78.2,15.4,6.4,83.4,10.4,6.3,85.0,8.2,6.7,86.3,6.4,7.3,87.7,3.7,8.6,61.8,2.4,35.8,84.2,2.0,13.8,84.2,1.5,14.3,73.6,2.0,24.5,81.6,1.9,16.5,87.4,1.2,11.5,88.2,4.3,7.6
69,Pailin,2020,75.4,16.5,8.1,84.6,8.6,6.9,85.3,7.8,6.8,83.3,5.7,11.0,85.4,5.5,9.1,65.6,1.3,33.1,83.4,1.4,15.2,83.7,0.8,15.5,71.6,5.1,23.3,84.8,2.0,13.2,88.2,0.9,10.9,71.7,3.8,24.4
70,Phnom Penh,2020,80.6,10.5,8.9,88.1,7.1,4.7,89.6,5.3,5.1,90.5,4.2,5.3,92.2,2.8,5.1,65.4,1.8,32.8,93.3,1.2,5.5,95.5,1.7,2.8,64.1,3.1,32.7,95.8,0.2,4.0,NaN,0.1,NaN,50.8,5.6,43.6
71,Preah Sihanouk,2020,77.5,15.7,6.8,83.0,11.1,5.9,85.1,7.4,7.5,88.6,5.9,5.5,88.6,3.5,7.9,76.2,3.4,20.4,87.4,1.6,11.0,89.1,0.6,10.3,76.2,3.7,20.2,88.8,0.3,10.9,89.4,0.1,10.6,77.7,1.1,21.2
72,Preah Vihear,2020,72.4,21.0,6.6,82.1,12.9,5.0,82.9,10.3,6.8,83.8,7.5,8.7,87.0,4.7,8.3,79.0,2.4,18.6,85.5,0.6,13.9,87.6,0.2,12.1,81.5,0.6,17.9,80.0,0.6,19.4,87.6,0.1,12.3,59.5,0.9,39.5
73,Prey Veng,2020,84.2,13.0,2.8,88.3,9.3,2.4,88.7,8.3,3.0,90.0,6.3,3.6,90.7,5.2,4.2,73.5,4.0,22.4,88.7,0.2,11.1,86.2,0.1,13.7,63.9,1.1,35.0,84.2,0.2,15.6,90.2,0.2,9.6,57.1,2.8,40.1
74,Pursat,2020,81.2,15.2,3.6,82.8,11.1,6.1,86.3,9.5,4.2,87.4,6.1,6.4,88.7,4.7,6.5,75.9,3.5,20.6,87.6,0.2,12.2,86.5,0.2,13.4,79.8,0.8,19.5,87.5,0.0,12.5,91.8,0.0,8.2,66.1,3.7,30.2
75,Ratanak Kiri,2020,81.4,8.7,9.8,85.7,6.6,7.7,86.3,5.3,8.4,85.3,4.1,10.6,84.6,2.9,12.5,66.8,2.4,30.8,84.5,0.1,15.4,90.0,0.0,10.0,58.9,3.1,38.0,82.3,0.3,17.4,88.8,0.0,11.2,79.3,1.6,19.1
76,Siemreap,2020,77.4,17.4,5.2,82.9,11.5,5.6,85.9,9.1,4.9,87.1,6.6,6.3,87.3,5.5,7.2,67.3,3.7,29.0,85.8,2.6,11.6,86.8,2.0,11.2,68.6,2.3,29.1,87.6,1.1,11.3,91.8,0.9,7.3,62.7,2.0,35.2
77,Stung Treng,2020,71.5,22.9,5.6,78.8,14.7,6.4,81.3,11.1,7.6,82.6,8.6,8.8,85.1,6.0,8.9,46.5,4.6,49.0,79.4,0.7,19.8,86.6,0.5,12.9,65.8,0.9,33.3,88.1,0.1,11.8,94.7,0.1,5.2,84.9,1.5,13.6
78,Svay Rieng,2020,86.6,10.9,2.5,90.3,6.6,3.2,92.0,5.2,2.8,92.1,4.6,3.2,92.5,3.2,4.3,74.4,2.4,23.1,85.8,0.5,13.7,81.0,0.3,18.7,59.6,1.0,39.4,81.8,0.0,18.2,87.3,0.0,12.6,50.6,1.2,48.2
80,Tbaung Khmum,2020,80.5,14.6,4.9,83.2,10.3,6.5,85.9,8.3,5.8,86.4,6.2,7.4,87.1,5.2,7.7,59.2,3.3,37.5,85.5,1.0,13.5,84.1,0.6,15.3,55.6,3.2,41.2,84.3,0.5,15.3,91.6,0.4,8.0,53.2,3.0,43.8
81,Whole Kingdom,2020,82.1,13.6,4.3,85.5,9.7,4.8,87.4,7.8,4.8,88.3,6.0,5.7,89.0,4.6,6.4,73.4,3.3,23.3,87.2,1.0,11.8,86.5,0.9,12.6,69.4,1.9,28.7,86.5,0.5,13.1,91.6,0.4,8.0,59.2,2.7,38.1
82,- Urban Area,2020,78.8,14.6,6.6,85.3,9.4,5.3,88.3,6.9,4.8,89.3,5.1,5.6,90.8,3.4,5.7,69.2,2.2,28.6,91.1,1.5,7.4,93.0,1.4,5.6,71.6,2.8,25.6,91.9,0.6,7.6,98.2,0.3,1.5,54.7,3.8,41.5
83,- Rural Area,2020,82.8,13.4,3.8,85.5,9.8,4.7,87.2,8.0,4.8,88.1,6.2,5.7,88.7,4.8,6.5,74.3,3.6,22.1,86.2,0.9,12.9,84.8,0.8,14.4,68.7,1.7,29.6,84.4,0.4,15.2,88.8,0.4,10.8,61.3,2.3,36.5

# summarize

In [441]:
df['Grade_6_Dropout'].mean()

np.float64(17.789285714285715)

In [442]:
df['Grade_6_Dropout'].min()

np.float64(2.1)

In [443]:
df['Grade_6_Dropout'].max()

np.float64(75.5)

In [444]:
df['Grade_6_Dropout'].std()

np.float64(13.11261709936244)

In [445]:
df['Grade_6_Dropout'].var()

np.float64(171.94072719449227)

In [446]:
df['Grade_6_Dropout'].count()

np.int64(84)

In [447]:
df['Grade_6_Dropout'].sum()

np.float64(1494.3)

In [448]:
df['Grade_6_Dropout'].quantile(0.25)

np.float64(6.675)

In [449]:
# quantile can also be a list
df['Grade_6_Dropout'].quantile([0.25,0.75])

0.25     6.675
0.75    24.325
Name: Grade_6_Dropout, dtype: float64

In [450]:
# all of these stuff can be run on multipul column at a time but i'm too lazy and stupid to show
# if we do that the result will return in serie

In [451]:
# we can write multipul statistic by using the agg function
df[['Year','Grade_2_Promotion','Grade_5_Promotion']].agg(['mean','min','max'])

        Year  Grade_2_Promotion  Grade_5_Promotion
mean  2019.0          88.359524          90.886747
min   2018.0          78.400000          82.100000
max   2020.0          98.800000          98.700000

In [452]:
# we can also do it in dictionalry if you wish to die

df[['Year','Grade_2_Promotion','Grade_5_Promotion']].agg({
    'Year':['sum','min'],
    'Grade_2_Promotion':'mean',
    'Grade_5_Promotion':'min'
    })

          Year  Grade_2_Promotion  Grade_5_Promotion
sum   169596.0                NaN                NaN
min     2018.0                NaN               82.1
mean       NaN          88.359524                NaN

In [453]:
df['Year'].unique()
# return all the unique value

array([2018, 2019, 2020])

In [454]:
df['Year'].nunique()
# retuen the amount of unique value

3

In [455]:
df['Year'].value_counts()
# go count each value

Year
2018    28
2019    28
2020    28
Name: count, dtype: int64

In [456]:
df['Year'].value_counts(normalize=True)
# give u percentage

Year
2018    0.333333
2019    0.333333
2020    0.333333
Name: proportion, dtype: float64

In [457]:
df[['Year','Grade_2_Promotion']].value_counts()
# go count each value combanation

Year  Grade_2_Promotion
2018  85.2                 2
      84.5                 2
2019  93.9                 2
2020  88.1                 2
      88.3                 2
                          ..
      86.2                 1
      89.6                 1
      89.9                 1
      90.3                 1
      90.5                 1
Name: count, Length: 74, dtype: int64

# advance cllumns method

In [458]:
df[['Grade_6_Dropout']].rank()
# compute the numirical data rank along the axis do not ask me wha that mean i have no idea

    Grade_6_Dropout
0              19.0
1              26.5
2               9.0
3               7.0
4               4.5
..              ...
79             32.0
80             80.0
81             62.0
82             66.0
83             57.0

[84 rows x 1 columns]

In [459]:
df[['Grade_6_Dropout']].shift(3)
# shift the index

    Grade_6_Dropout
0               NaN
1               NaN
2               NaN
3               6.4
4               8.6
..              ...
79             29.0
80             49.0
81             23.1
82             10.3
83             37.5

[84 rows x 1 columns]

In [460]:
df[['Grade_6_Dropout']].shift(3,fill_value=0)
# when shift the first number will ne nan we can fill it with 0

    Grade_6_Dropout
0               0.0
1               0.0
2               0.0
3               6.4
4               8.6
..              ...
79             29.0
80             49.0
81             23.1
82             10.3
83             37.5

[84 rows x 1 columns]

In [461]:
df[['Grade_6_Dropout']].cumsum()
# do cdf unfotunetly number can not cum

    Grade_6_Dropout
0               6.4
1              15.0
2              19.9
3              23.9
4              27.4
..              ...
79           1382.8
80           1420.3
81           1443.6
82           1472.2
83           1494.3

[84 rows x 1 columns]

In [462]:
df[['Grade_6_Dropout']].rolling(window=5).mean()
# calculate rolling window i dk what that mean

    Grade_6_Dropout
0               NaN
1               NaN
2               NaN
3               NaN
4              5.48
..              ...
79            28.44
80            29.78
81            28.64
82            24.56
83            24.36

[84 rows x 1 columns]

In [463]:
df[['Grade_6_Dropout']].clip(3,6)
# this clip value to the number in this parameter

    Grade_6_Dropout
0               6.0
1               6.0
2               4.9
3               4.0
4               3.5
..              ...
79              6.0
80              6.0
81              6.0
82              6.0
83              6.0

[84 rows x 1 columns]

# groupby method

In [464]:
# group by a coulumn
df_agg=df.groupby('Year')[['Grade_1_Dropout','Grade_2_Dropout','Grade_3_Dropout','Grade_4_Dropout']].agg(['mean','min','max'])

In [465]:
df_agg.columns = ['_'.join(c) for c in df_agg.columns]

In [466]:
df_agg

,Grade_1_Dropout_mean,Grade_1_Dropout_min,Grade_1_Dropout_max,Grade_2_Dropout_mean,Grade_2_Dropout_min,Grade_2_Dropout_max,Grade_3_Dropout_mean,Grade_3_Dropout_min,Grade_3_Dropout_max,Grade_4_Dropout_mean,Grade_4_Dropout_min,Grade_4_Dropout_max
Year,,,,,,,,,,,,
2018,3.970370,1.0,11.7,4.02963,1.0,10.2,4.528571,0.4,10.0,5.421429,1.5,13.8
2019,4.055556,0.3,12.0,3.52000,0.2,11.5,4.184615,1.0,11.3,4.566667,0.2,15.0
2020,4.871429,1.5,9.8,5.12500,2.4,8.8,5.271429,2.4,8.4,6.453571,3.0,11.0

# make new columns

In [467]:
df['drop_out'] = df[["Grade_1_Dropout","Grade_2_Dropout","Grade_3_Dropout","Grade_4_Dropout","Grade_5_Dropout","Grade_6_Dropout","Grade_7_Dropout","Grade_8_Dropout","Grade_9_Dropout","Grade_10_Dropout","Grade_11_Dropout","Grade_12_Dropout"]].sum(axis=1)

In [468]:
df

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout,drop_out
0,Banteay Meanchey,2018,90.7,6.0,3.3,91.6,4.7,3.7,94.7,3.4,2.0,91.0,2.5,6.4,95.0,1.6,3.4,92.3,1.3,6.4,80.4,2.2,17.3,84.4,1.6,14.0,78.7,2.8,18.4,85.6,0.6,13.8,89.7,0.7,9.6,54.9,5.5,39.7,138.0
1,Battambang,2018,83.8,11.7,4.5,88.5,8.0,3.6,88.6,5.7,5.7,90.8,4.0,5.2,91.0,2.7,6.3,89.1,2.3,8.6,76.8,3.3,19.9,81.3,2.2,16.5,78.7,4.3,17.0,82.4,1.2,16.4,87.5,1.2,11.3,66.1,4.6,29.3,144.3
2,Kampong Cham,2018,81.6,14.2,4.2,84.4,10.9,4.7,86.5,8.9,4.6,88.0,7.4,4.6,89.8,5.8,4.4,91.2,3.9,4.9,80.1,3.3,16.6,82.1,2.6,15.2,79.5,3.3,17.2,80.0,2.0,18.1,89.9,0.6,9.5,56.6,5.3,38.1,142.1
3,Kampong Chhnang,2018,88.0,10.6,1.4,90.3,7.6,2.0,91.5,6.3,2.2,92.5,4.5,3.0,94.5,2.8,2.7,94.0,2.0,4.0,83.5,2.4,14.1,83.3,1.5,15.1,82.0,2.3,15.7,81.9,0.8,17.3,89.2,0.6,10.2,60.2,5.2,34.6,122.3
4,Kampong Speu,2018,89.3,8.7,2.0,92.5,6.3,1.2,92.7,4.5,2.8,93.2,3.3,3.5,92.7,2.4,4.9,93.4,3.1,3.5,79.5,1.3,19.2,80.6,0.7,18.6,75.1,2.2,22.7,79.4,0.3,20.3,89.4,0.2,10.4,84.4,1.9,13.7,122.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Takeo,2020,85.6,12.3,2.1,88.1,9.3,2.6,89.4,7.9,2.7,90.8,6.2,3.0,91.5,5.1,3.4,85.4,4.2,10.3,91.9,1.3,6.9,88.8,1.9,9.3,77.8,1.3,20.9,89.3,0.3,10.4,89.3,0.3,10.4,65.3,2.2,32.5,114.5
80,Tbaung Khmum,2020,80.5,14.6,4.9,83.2,10.3,6.5,85.9,8.3,5.8,86.4,6.2,7.4,87.1,5.2,7.7,59.2,3.3,37.5,85.5,1.0,13.5,84.1,0.6,15.3,55.6,3.2,41.2,84.3,0.5,15.3,91.6,0.4,8.0,53.2,3.0,43.8,206.9
81,Whole Kingdom,2020,82.1,13.6,4.3,85.5,9.7,4.8,87.4,7.8,4.8,88.3,6.0,5.7,89.0,4.6,6.4,73.4,3.3,23.3,87.2,1.0,11.8,86.5,0.9,12.6,69.4,1.9,28.7,86.5,0.5,13.1,91.6,0.4,8.0,59.2,2.7,38.1,161.6
82,- Urban Area,2020,78.8,14.6,6.6,85.3,9.4,5.3,88.3,6.9,4.8,89.3,5.1,5.6,90.8,3.4,5.7,69.2,2.2,28.6,91.1,1.5,7.4,93.0,1.4,5.6,71.6,2.8,25.6,91.9,0.6,7.6,98.2,0.3,1.5,54.7,3.8,41.5,145.8
83,- Rural Area,2020,82.8,13.4,3.8,85.5,9.8,4.7,87.2,8.0,4.8,88.1,6.2,5.7,88.7,4.8,6.5,74.3,3.6,22.1,86.2,0.9,12.9,84.8,0.8,14.4,68.7,1.7,29.6,84.4,0.4,15.2,88.8,0.4,10.8,61.3,2.3,36.5,167.0

In [469]:
df.assign(drop_out_avg=df['drop_out'].mean())

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout,drop_out,drop_out_avg
0,Banteay Meanchey,2018,90.7,6.0,3.3,91.6,4.7,3.7,94.7,3.4,2.0,91.0,2.5,6.4,95.0,1.6,3.4,92.3,1.3,6.4,80.4,2.2,17.3,84.4,1.6,14.0,78.7,2.8,18.4,85.6,0.6,13.8,89.7,0.7,9.6,54.9,5.5,39.7,138.0,143.322619
1,Battambang,2018,83.8,11.7,4.5,88.5,8.0,3.6,88.6,5.7,5.7,90.8,4.0,5.2,91.0,2.7,6.3,89.1,2.3,8.6,76.8,3.3,19.9,81.3,2.2,16.5,78.7,4.3,17.0,82.4,1.2,16.4,87.5,1.2,11.3,66.1,4.6,29.3,144.3,143.322619
2,Kampong Cham,2018,81.6,14.2,4.2,84.4,10.9,4.7,86.5,8.9,4.6,88.0,7.4,4.6,89.8,5.8,4.4,91.2,3.9,4.9,80.1,3.3,16.6,82.1,2.6,15.2,79.5,3.3,17.2,80.0,2.0,18.1,89.9,0.6,9.5,56.6,5.3,38.1,142.1,143.322619
3,Kampong Chhnang,2018,88.0,10.6,1.4,90.3,7.6,2.0,91.5,6.3,2.2,92.5,4.5,3.0,94.5,2.8,2.7,94.0,2.0,4.0,83.5,2.4,14.1,83.3,1.5,15.1,82.0,2.3,15.7,81.9,0.8,17.3,89.2,0.6,10.2,60.2,5.2,34.6,122.3,143.322619
4,Kampong Speu,2018,89.3,8.7,2.0,92.5,6.3,1.2,92.7,4.5,2.8,93.2,3.3,3.5,92.7,2.4,4.9,93.4,3.1,3.5,79.5,1.3,19.2,80.6,0.7,18.6,75.1,2.2,22.7,79.4,0.3,20.3,89.4,0.2,10.4,84.4,1.9,13.7,122.8,143.322619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Takeo,2020,85.6,12.3,2.1,88.1,9.3,2.6,89.4,7.9,2.7,90.8,6.2,3.0,91.5,5.1,3.4,85.4,4.2,10.3,91.9,1.3,6.9,88.8,1.9,9.3,77.8,1.3,20.9,89.3,0.3,10.4,89.3,0.3,10.4,65.3,2.2,32.5,114.5,143.322619
80,Tbaung Khmum,2020,80.5,14.6,4.9,83.2,10.3,6.5,85.9,8.3,5.8,86.4,6.2,7.4,87.1,5.2,7.7,59.2,3.3,37.5,85.5,1.0,13.5,84.1,0.6,15.3,55.6,3.2,41.2,84.3,0.5,15.3,91.6,0.4,8.0,53.2,3.0,43.8,206.9,143.322619
81,Whole Kingdom,2020,82.1,13.6,4.3,85.5,9.7,4.8,87.4,7.8,4.8,88.3,6.0,5.7,89.0,4.6,6.4,73.4,3.3,23.3,87.2,1.0,11.8,86.5,0.9,12.6,69.4,1.9,28.7,86.5,0.5,13.1,91.6,0.4,8.0,59.2,2.7,38.1,161.6,143.322619
82,- Urban Area,2020,78.8,14.6,6.6,85.3,9.4,5.3,88.3,6.9,4.8,89.3,5.1,5.6,90.8,3.4,5.7,69.2,2.2,28.6,91.1,1.5,7.4,93.0,1.4,5.6,71.6,2.8,25.6,91.9,0.6,7.6,98.2,0.3,1.5,54.7,3.8,41.5,145.8,143.322619
83,- Rural Area,2020,82.8,13.4,3.8,85.5,9.8,4.7,87.2,8.0,4.8,88.1,6.2,5.7,88.7,4.8,6.5,74.3,3.6,22.1,86.2,0.9,12.9,84.8,0.8,14.4,68.7,1.7,29.6,84.4,0.4,15.2,88.8,0.4,10.8,61.3,2.3,36.5,167.0,143.322619

# sorting data

In [470]:
df.sort_values('drop_out')
# lowest to highest

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout,drop_out
35,Kandal,2019,88.6,10.4,1.0,90.7,7.2,2.1,93.0,5.9,1.1,92.7,4.3,2.9,93.9,3.5,2.5,95.2,2.2,2.6,85.9,1.8,12.3,86.7,1.1,12.2,87.5,1.6,10.9,85.8,0.8,13.4,88.4,0.4,11.2,80.1,2.9,17.0,89.2
14,Phnom Penh,2018,90.8,5.6,3.6,93.2,4.0,2.8,94.0,2.7,3.3,96.1,2.0,1.9,95.0,1.8,3.2,94.2,0.8,5.0,85.1,3.2,11.7,92.8,2.3,4.9,86.6,3.3,10.1,90.8,1.1,8.0,NaN,1.1,NaN,49.0,6.9,44.1,98.6
36,Kep,2019,91.6,12.1,NaN,98.8,7.5,NaN,92.6,7.6,NaN,94.4,5.8,NaN,94.5,1.4,4.1,84.7,1.3,14.1,74.9,1.9,23.2,84.5,1.2,14.3,75.7,4.3,20.0,90.3,1.5,8.2,92.4,0.0,7.6,91.1,1.1,7.8,99.3
26,- Urban Area,2018,87.3,8.8,3.9,90.4,5.8,3.7,92.9,4.2,3.0,95.0,2.8,2.2,94.2,2.1,3.7,92.6,1.1,6.3,82.3,3.7,14.1,91.0,2.2,6.8,84.6,3.8,11.6,89.8,1.3,8.9,98.8,1.0,0.2,58.1,5.3,36.7,101.1
20,Siemreap,2018,82.9,13.8,3.4,85.2,9.2,5.7,88.3,7.1,4.5,93.8,4.8,1.5,91.4,3.6,5.0,88.6,2.7,8.7,80.0,4.6,15.4,86.2,2.9,10.9,82.0,4.4,13.6,93.5,2.3,4.2,92.7,1.2,6.1,72.4,3.6,24.0,103.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Ratanak Kiri,2020,81.4,8.7,9.8,85.7,6.6,7.7,86.3,5.3,8.4,85.3,4.1,10.6,84.6,2.9,12.5,66.8,2.4,30.8,84.5,0.1,15.4,90.0,0.0,10.0,58.9,3.1,38.0,82.3,0.3,17.4,88.8,0.0,11.2,79.3,1.6,19.1,190.9
52,Tbaung Khmum,2019,86.0,8.5,5.5,88.9,5.9,5.3,89.5,4.5,6.1,91.3,3.2,5.6,90.1,2.8,7.1,49.8,1.4,48.8,79.3,2.2,18.5,81.6,1.4,16.9,56.4,2.6,41.0,90.0,1.2,8.9,91.2,0.3,8.5,75.1,2.2,22.6,194.8
80,Tbaung Khmum,2020,80.5,14.6,4.9,83.2,10.3,6.5,85.9,8.3,5.8,86.4,6.2,7.4,87.1,5.2,7.7,59.2,3.3,37.5,85.5,1.0,13.5,84.1,0.6,15.3,55.6,3.2,41.2,84.3,0.5,15.3,91.6,0.4,8.0,53.2,3.0,43.8,206.9
60,Kampong Speu,2020,87.1,10.1,2.9,90.5,6.3,3.2,90.0,6.1,3.9,90.8,4.9,4.3,90.7,3.4,5.9,66.4,2.7,30.9,81.0,0.5,18.5,79.6,0.5,19.9,45.2,1.6,53.2,77.6,0.6,21.8,86.5,0.6,13.0,36.0,1.1,62.9,240.4
43,Preah Sihanouk,2019,88.4,5.6,5.9,94.4,3.9,1.7,93.7,3.4,2.9,92.0,2.0,6.0,97.8,1.3,0.9,23.5,1.0,75.5,76.5,2.3,21.2,83.6,2.1,14.2,13.0,3.6,83.4,87.3,0.9,11.8,76.9,0.1,23.0,73.7,18.5,7.8,254.3

In [471]:
df = df.sort_values(['drop_out', 'Year'], ascending=[False, False]).reset_index(drop=True)

# Handling missing data

In [472]:
df.isna()
# will say true if daya is missing

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout,drop_out
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
80,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
81,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
82,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False
83,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [473]:
df.isna().sum()

Province               0
Year                   0
Grade_1_Promotion      0
Grade_1_Repetition     0
Grade_1_Dropout        2
Grade_2_Promotion      0
Grade_2_Repetition     0
Grade_2_Dropout        4
Grade_3_Promotion      0
Grade_3_Repetition     0
Grade_3_Dropout        2
Grade_4_Promotion      0
Grade_4_Repetition     0
Grade_4_Dropout        1
Grade_5_Promotion      1
Grade_5_Repetition     0
Grade_5_Dropout        1
Grade_6_Promotion      0
Grade_6_Repetition     0
Grade_6_Dropout        0
Grade_7_Promotion      0
Grade_7_Repetition     0
Grade_7_Dropout        0
Grade_8_Promotion      0
Grade_8_Repetition     0
Grade_8_Dropout        0
Grade_9_Promotion      0
Grade_9_Repetition     0
Grade_9_Dropout        0
Grade_10_Promotion     1
Grade_10_Repetition    0
Grade_10_Dropout       1
Grade_11_Promotion     3
Grade_11_Repetition    0
Grade_11_Dropout       4
Grade_12_Promotion     0
Grade_12_Repetition    0
Grade_12_Dropout       0
drop_out               0
dtype: int64

In [474]:
df.dropna()

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout,drop_out
0,Preah Sihanouk,2019,88.4,5.6,5.9,94.4,3.9,1.7,93.7,3.4,2.9,92.0,2.0,6.0,97.8,1.3,0.9,23.5,1.0,75.5,76.5,2.3,21.2,83.6,2.1,14.2,13.0,3.6,83.4,87.3,0.9,11.8,76.9,0.1,23.0,73.7,18.5,7.8,254.3
1,Kampong Speu,2020,87.1,10.1,2.9,90.5,6.3,3.2,90.0,6.1,3.9,90.8,4.9,4.3,90.7,3.4,5.9,66.4,2.7,30.9,81.0,0.5,18.5,79.6,0.5,19.9,45.2,1.6,53.2,77.6,0.6,21.8,86.5,0.6,13.0,36.0,1.1,62.9,240.4
2,Tbaung Khmum,2020,80.5,14.6,4.9,83.2,10.3,6.5,85.9,8.3,5.8,86.4,6.2,7.4,87.1,5.2,7.7,59.2,3.3,37.5,85.5,1.0,13.5,84.1,0.6,15.3,55.6,3.2,41.2,84.3,0.5,15.3,91.6,0.4,8.0,53.2,3.0,43.8,206.9
3,Tbaung Khmum,2019,86.0,8.5,5.5,88.9,5.9,5.3,89.5,4.5,6.1,91.3,3.2,5.6,90.1,2.8,7.1,49.8,1.4,48.8,79.3,2.2,18.5,81.6,1.4,16.9,56.4,2.6,41.0,90.0,1.2,8.9,91.2,0.3,8.5,75.1,2.2,22.6,194.8
4,Ratanak Kiri,2020,81.4,8.7,9.8,85.7,6.6,7.7,86.3,5.3,8.4,85.3,4.1,10.6,84.6,2.9,12.5,66.8,2.4,30.8,84.5,0.1,15.4,90.0,0.0,10.0,58.9,3.1,38.0,82.3,0.3,17.4,88.8,0.0,11.2,79.3,1.6,19.1,190.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Kep,2020,83.6,11.6,4.7,89.9,7.7,2.4,89.9,4.2,6.0,88.6,2.4,9.0,88.7,2.6,8.7,83.6,1.2,15.2,89.0,0.6,10.3,90.0,0.6,9.4,79.6,9.1,11.3,91.8,0.0,8.2,94.1,0.0,5.9,84.6,0.3,15.0,106.1
77,Siemreap,2019,86.5,11.1,2.4,90.6,7.1,2.2,92.5,4.8,2.7,94.1,2.9,3.0,95.8,2.0,2.2,84.5,1.3,14.2,84.3,2.6,13.1,86.2,1.5,12.3,82.3,2.2,15.5,85.6,1.4,13.1,94.1,0.7,5.2,78.9,1.5,19.6,105.5
79,Siemreap,2018,82.9,13.8,3.4,85.2,9.2,5.7,88.3,7.1,4.5,93.8,4.8,1.5,91.4,3.6,5.0,88.6,2.7,8.7,80.0,4.6,15.4,86.2,2.9,10.9,82.0,4.4,13.6,93.5,2.3,4.2,92.7,1.2,6.1,72.4,3.6,24.0,103.0
80,- Urban Area,2018,87.3,8.8,3.9,90.4,5.8,3.7,92.9,4.2,3.0,95.0,2.8,2.2,94.2,2.1,3.7,92.6,1.1,6.3,82.3,3.7,14.1,91.0,2.2,6.8,84.6,3.8,11.6,89.8,1.3,8.9,98.8,1.0,0.2,58.1,5.3,36.7,101.1
83,Kandal,2019,88.6,10.4,1.0,90.7,7.2,2.1,93.0,5.9,1.1,92.7,4.3,2.9,93.9,3.5,2.5,95.2,2.2,2.6,85.9,1.8,12.3,86.7,1.1,12.2,87.5,1.6,10.9,85.8,0.8,13.4,88.4,0.4,11.2,80.1,2.9,17.0,89.2

In [475]:
df.fillna(0)

,Province,Year,Grade_1_Promotion,Grade_1_Repetition,Grade_1_Dropout,Grade_2_Promotion,Grade_2_Repetition,Grade_2_Dropout,Grade_3_Promotion,Grade_3_Repetition,Grade_3_Dropout,Grade_4_Promotion,Grade_4_Repetition,Grade_4_Dropout,Grade_5_Promotion,Grade_5_Repetition,Grade_5_Dropout,Grade_6_Promotion,Grade_6_Repetition,Grade_6_Dropout,Grade_7_Promotion,Grade_7_Repetition,Grade_7_Dropout,Grade_8_Promotion,Grade_8_Repetition,Grade_8_Dropout,Grade_9_Promotion,Grade_9_Repetition,Grade_9_Dropout,Grade_10_Promotion,Grade_10_Repetition,Grade_10_Dropout,Grade_11_Promotion,Grade_11_Repetition,Grade_11_Dropout,Grade_12_Promotion,Grade_12_Repetition,Grade_12_Dropout,drop_out
0,Preah Sihanouk,2019,88.4,5.6,5.9,94.4,3.9,1.7,93.7,3.4,2.9,92.0,2.0,6.0,97.8,1.3,0.9,23.5,1.0,75.5,76.5,2.3,21.2,83.6,2.1,14.2,13.0,3.6,83.4,87.3,0.9,11.8,76.9,0.1,23.0,73.7,18.5,7.8,254.3
1,Kampong Speu,2020,87.1,10.1,2.9,90.5,6.3,3.2,90.0,6.1,3.9,90.8,4.9,4.3,90.7,3.4,5.9,66.4,2.7,30.9,81.0,0.5,18.5,79.6,0.5,19.9,45.2,1.6,53.2,77.6,0.6,21.8,86.5,0.6,13.0,36.0,1.1,62.9,240.4
2,Tbaung Khmum,2020,80.5,14.6,4.9,83.2,10.3,6.5,85.9,8.3,5.8,86.4,6.2,7.4,87.1,5.2,7.7,59.2,3.3,37.5,85.5,1.0,13.5,84.1,0.6,15.3,55.6,3.2,41.2,84.3,0.5,15.3,91.6,0.4,8.0,53.2,3.0,43.8,206.9
3,Tbaung Khmum,2019,86.0,8.5,5.5,88.9,5.9,5.3,89.5,4.5,6.1,91.3,3.2,5.6,90.1,2.8,7.1,49.8,1.4,48.8,79.3,2.2,18.5,81.6,1.4,16.9,56.4,2.6,41.0,90.0,1.2,8.9,91.2,0.3,8.5,75.1,2.2,22.6,194.8
4,Ratanak Kiri,2020,81.4,8.7,9.8,85.7,6.6,7.7,86.3,5.3,8.4,85.3,4.1,10.6,84.6,2.9,12.5,66.8,2.4,30.8,84.5,0.1,15.4,90.0,0.0,10.0,58.9,3.1,38.0,82.3,0.3,17.4,88.8,0.0,11.2,79.3,1.6,19.1,190.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Siemreap,2018,82.9,13.8,3.4,85.2,9.2,5.7,88.3,7.1,4.5,93.8,4.8,1.5,91.4,3.6,5.0,88.6,2.7,8.7,80.0,4.6,15.4,86.2,2.9,10.9,82.0,4.4,13.6,93.5,2.3,4.2,92.7,1.2,6.1,72.4,3.6,24.0,103.0
80,- Urban Area,2018,87.3,8.8,3.9,90.4,5.8,3.7,92.9,4.2,3.0,95.0,2.8,2.2,94.2,2.1,3.7,92.6,1.1,6.3,82.3,3.7,14.1,91.0,2.2,6.8,84.6,3.8,11.6,89.8,1.3,8.9,98.8,1.0,0.2,58.1,5.3,36.7,101.1
81,Kep,2019,91.6,12.1,0.0,98.8,7.5,0.0,92.6,7.6,0.0,94.4,5.8,0.0,94.5,1.4,4.1,84.7,1.3,14.1,74.9,1.9,23.2,84.5,1.2,14.3,75.7,4.3,20.0,90.3,1.5,8.2,92.4,0.0,7.6,91.1,1.1,7.8,99.3
82,Phnom Penh,2018,90.8,5.6,3.6,93.2,4.0,2.8,94.0,2.7,3.3,96.1,2.0,1.9,95.0,1.8,3.2,94.2,0.8,5.0,85.1,3.2,11.7,92.8,2.3,4.9,86.6,3.3,10.1,90.8,1.1,8.0,0.0,1.1,0.0,49.0,6.9,44.1,98.6
83,Kandal,2019,88.6,10.4,1.0,90.7,7.2,2.1,93.0,5.9,1.1,92.7,4.3,2.9,93.9,3.5,2.5,95.2,2.2,2.6,85.9,1.8,12.3,86.7,1.1,12.2,87.5,1.6,10.9,85.8,0.8,13.4,88.4,0.4,11.2,80.1,2.9,17.0,89.2

In [476]:
df['Grade_2_Dropout'].fillna(df['Grade_2_Dropout'].mean())

0     1.70000
1     3.20000
2     6.50000
3     5.30000
4     7.70000
       ...
79    5.70000
80    3.70000
81    4.25375
82    2.80000
83    2.10000
Name: Grade_2_Dropout, Length: 84, dtype: float64

# combining data

In [477]:
df1=df[['Year','Grade_2_Dropout']].copy()
df2=df[['Year','Grade_3_Dropout']].copy()

In [478]:
df_stack = pd.concat([df1,df2])

In [479]:
df_stack

    Year  Grade_2_Dropout  Grade_3_Dropout
0   2019              1.7              NaN
1   2020              3.2              NaN
2   2020              6.5              NaN
3   2019              5.3              NaN
4   2020              7.7              NaN
..   ...              ...              ...
79  2018              NaN              4.5
80  2018              NaN              3.0
81  2019              NaN              NaN
82  2018              NaN              3.3
83  2019              NaN              1.1

[168 rows x 3 columns]

In [480]:
df1=df[['Year','Grade_2_Dropout']].reset_index(drop=True)
df2=df[['Year','Grade_3_Dropout']].reset_index(drop=True)
df_side = pd.concat([df1,df2],axis=1)

In [481]:
df_side

    Year  Grade_2_Dropout  Year  Grade_3_Dropout
0   2019              1.7  2019              2.9
1   2020              3.2  2020              3.9
2   2020              6.5  2020              5.8
3   2019              5.3  2019              6.1
4   2020              7.7  2020              8.4
..   ...              ...   ...              ...
79  2018              5.7  2018              4.5
80  2018              3.7  2018              3.0
81  2019              NaN  2019              NaN
82  2018              2.8  2018              3.3
83  2019              2.1  2019              1.1

[84 rows x 4 columns]

# merge

In [482]:
df1=df.groupby('Year')[['Grade_1_Dropout','Grade_2_Dropout','Grade_3_Dropout','Grade_4_Dropout']].agg(['mean','min','max'])
df2=df.groupby('Year')[['Grade_5_Dropout','Grade_6_Dropout','Grade_7_Dropout','Grade_8_Dropout']].agg(['mean','min','max'])

In [483]:
df1.merge(df2, left_index=True, right_index=True)

     Grade_1_Dropout            Grade_2_Dropout            Grade_3_Dropout  \
                mean  min   max            mean  min   max            mean
Year
2018        3.970370  1.0  11.7         4.02963  1.0  10.2        4.528571
2019        4.055556  0.3  12.0         3.52000  0.2  11.5        4.184615
2020        4.871429  1.5   9.8         5.12500  2.4   8.8        5.271429

                Grade_4_Dropout            Grade_5_Dropout             \
      min   max            mean  min   max            mean  min   max
Year
2018  0.4  10.0        5.421429  1.5  13.8        5.835714  0.0  14.1
2019  1.0  11.3        4.566667  0.2  15.0        4.822222  0.9  12.1
2020  2.4   8.4        6.453571  3.0  11.0        7.096429  3.4  12.5

     Grade_6_Dropout            Grade_7_Dropout             Grade_8_Dropout  \
                mean  min   max            mean   min   max            mean
Year
2018        7.692857  2.1  22.6       17.467857  11.5  23.2       13.628571
2019       21.200000  2.6  75.5       15.353571   7.1  23.2       13.625000
2020       24.475000  3.9  49.0       12.503571   5.5  19.8       12.732143


      min   max
Year
2018  1.0  20.6
2019  1.6  21.6
2020  2.8  19.9

In [484]:
# 1. Group and Aggregate
df1 = df.groupby('Year')[['Grade_1_Dropout', 'Grade_2_Dropout']].agg(['mean', 'min', 'max'])
df2 = df.groupby('Year')[['Grade_5_Dropout', 'Grade_6_Dropout']].agg(['mean', 'min', 'max'])

# 2. Flatten the MultiIndex Columns
# This joins 'Grade_1_Dropout' and 'mean' into 'Grade_1_Dropout_mean'
df1.columns = ['_'.join(col).strip() for col in df1.columns.values]
df2.columns = ['_'.join(col).strip() for col in df2.columns.values]

# 3. Perform the Merge
# We use reset_index() so 'Year' becomes a regular column we can use with 'on'
final_df = df1.reset_index().merge(
    df2.reset_index(), 
    on='Year', 
    how='inner',       # Only keeps years present in both
    indicator=True     # Adds a column showing where the row came from
)

print(final_df.head())

   Year  Grade_1_Dropout_mean  Grade_1_Dropout_min  Grade_1_Dropout_max  \
0  2018              3.970370                  1.0                 11.7
1  2019              4.055556                  0.3                 12.0
2  2020              4.871429                  1.5                  9.8

   Grade_2_Dropout_mean  Grade_2_Dropout_min  Grade_2_Dropout_max  \
0               4.02963                  1.0                 10.2
1               3.52000                  0.2                 11.5
2               5.12500                  2.4                  8.8

   Grade_5_Dropout_mean  Grade_5_Dropout_min  Grade_5_Dropout_max  \
0              5.835714                  0.0                 14.1
1              4.822222                  0.9                 12.1
2              7.096429                  3.4                 12.5

   Grade_6_Dropout_mean  Grade_6_Dropout_min  Grade_6_Dropout_max _merge
0              7.692857                  2.1                 22.6   both
1             21.200000                  2.6                 75.5   both
2             24.475000                  3.9                 49.0   both

In [485]:
df1.merge(df2, on='Year')

,Grade_1_Dropout_mean,Grade_1_Dropout_min,Grade_1_Dropout_max,Grade_2_Dropout_mean,Grade_2_Dropout_min,Grade_2_Dropout_max,Grade_5_Dropout_mean,Grade_5_Dropout_min,Grade_5_Dropout_max,Grade_6_Dropout_mean,Grade_6_Dropout_min,Grade_6_Dropout_max
Year,,,,,,,,,,,,
2018,3.970370,1.0,11.7,4.02963,1.0,10.2,5.835714,0.0,14.1,7.692857,2.1,22.6
2019,4.055556,0.3,12.0,3.52000,0.2,11.5,4.822222,0.9,12.1,21.200000,2.6,75.5
2020,4.871429,1.5,9.8,5.12500,2.4,8.8,7.096429,3.4,12.5,24.475000,3.9,49.0